# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'jubulife' do
	project 'jubulife.xcodeproj'
	pod 'Firebase/Messaging', '10.17.0'
end
